### ISSUE TITLE
We need fit PEP8 for each piece of code.

### ISSUE THREAD

**Issue by jackey8616** [YunOSC/PyFun-Backend#11]
As topic, hope there is anyone to help fitting PEP8 standard.
Reference at [here](https://www.python.org/dev/peps/pep-0008/?).

Before taking this issue. 
Plz comment below to let me know and tag a assign label.

**Comment by jackey8616** [comment]
@rozig  I can not assign you here. lol
Just tag you. :smile:

**Comment by rozig** [comment]
Ohh okay. So I take this.
